### ISSUE TITLE
onprogress

### ISSUE THREAD

**Issue by phiku** [naugtur/xhr#130]
Hi, 

is there a reason, why onprogress is filled with a placeholder to make IE happy, instead of let the programmer pass it as an option? The placeholder could be used, if the the options.onprogress is null or undefined. I ask, because I have not yet a proof, but the assumption, that setting onprogress after open can make problems in some browsers.

Greetings Philipp

**Comment by naugtur** [comment]
Hi,

I was focusing on other things as onprogress is not a part of `request` API that we're aiming at implementing in the browser.

But my thought in general was that `xhr` should allow passing this option in for those who really need it. 

Currently it should be possible to pass `beforeSend` function that accepts XMLHttpRequest object as argument and you can set anything on it. 

If you can find circumstances under which it fails, please let me know.

**Comment by naugtur** [comment]
Here's an example:

```js
xhr({
...
  beforeSend: function(xhrObject){
    xhrObject.onprogress = function(){}
  }
})
```
