### ISSUE TITLE
If-Modified-Since and Last-Modified: xhr option?

### ISSUE THREAD

**Issue by stuartsan** [naugtur/xhr#137]
I'm wondering if this project would consider a PR which adds something like `jQuery.ajax()`'s `ifModified` [xhr option](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings):

> Allow the request to be successful only if the response has changed since the last request. This is done by checking the Last-Modified header. Default value is false, ignoring the header. In jQuery 1.4 this technique also checks the 'etag' specified by the server to catch unmodified data.

The use case I'm interested in is passing through the 304 status code to the JS when a server supports `If-Modified-Since`/`Last-Modified` and a resource has not changed; without wiring up the `If-Modified-Since` request header manually, based on the previous `Last-Modified` response value, the browser will give the JS a 200 and the fact that it was not modified is lost. So this would provide a more convenient and library-level way to tack the `If-Modified-Since` header onto a request based on its previous `Last-Modified` time.

Some useful background on the situation is detailed [here](http://stackoverflow.com/a/12501696).

**Comment by stuartsan** [comment]
...also, considering this API is a subset of [request](https://github.com/request/request) please let me know if it might make more sense to open this issue there.

**Comment by naugtur** [comment]
But it's just a header. You can set it without adding code to xhr or any other library.

This looks like a good explanation http://stackoverflow.com/a/5081527

**Comment by stuartsan** [comment]
You can, though you have to maintain your own map of resources and their `Last-Modified` times to pass along as `If-Modified-Since` in the subsequent request. I was curious if this project would consider doing something like jQuery.ajax, i.e. [maintain this map for you at the library level](https://github.com/jquery/jquery/blob/master/src/ajax.js#L623), but it sounds like not.

**Comment by TehShrike** [comment]
I'll bet you could make a wrapper for `xhr`/`request` that could maintain that map.  It would probably be worth linking to the wrapper in the readme if it existed.

**Comment by naugtur** [comment]
We'd probably double the size of xhr adding this. 

I hope you can forgive us being too low level for this feature. :wink:

**Comment by stuartsan** [comment]
> We'd probably double the size of xhr adding this.

Ha ha yes, fair point 😄 

> I'll bet you could make a wrapper for xhr/request that could maintain that map

I may look into this approach. Thanks!
