### ISSUE TITLE
options.json === false

### ISSUE THREAD

**Issue by dhritzkiv** [naugtur/xhr#141]
Per the recent `json` option behaviour changes, where:

- `json: true` causes `body` to be serialized with `JSON.stringify`; and by extension,
- `true` is not a valid json value (anymore)

What should the behaviour for `json: false` be? By the logic of the second point (which I agree with), `false` should also not be a valid value.

However, passing `json: false`<sup>*</sup> currently results in "false" being sent, instead of disabling json behaviour.

###### <sup>*</sup> Passing `false` may be a desired thing to do if `json: true` is default behaviour for 99% of requests (for example, by using `ajaxConfig` in ampersand-sync), but you want to disable json behaviour for one request.

-----

I propose that L161 is changed from:

```js
if ("json" in options) {
```

to

```js
if ("json" in options && options.json !== false) {
```

To disable json behaviour when `json: false` is passed into the options.

This raises questions of what to do about `null` and `undefined`, but I think this is a good starting point, as `false` is very explicit and unambiguous.

Let me know your thoughts, and I can submit a PR!

**Comment by naugtur** [comment]
oops. 
I don't know how I overlooked that.

**Comment by naugtur** [comment]
I was also considering just changing it to 
```
if(options.json)
```
but that would break backward compatibility for POSTing to APIs that respond with JSON while accepting empty body (undefined) or null

This feels urgent to me, so I'm not going to wait too long before releasing it.

**Comment by dhritzkiv** [comment]
Seems

```js
if (options.json)
```

or more explicitly

```js
if (options.json === true)
```

and removing backwards compatibility of passing a body to `json` would be a candidate for v3.0

**Comment by naugtur** [comment]
Sounds good. Wanna do the honors and suggest that in the v3 roadmap discussion? :D
