### ISSUE TITLE
Is it possible to do the exact reverse of this lib?

### ISSUE THREAD

**Issue by thinkloop** [naugtur/xhr#143]
Hello,

I have been scouring the web for a lib that does the exact opposite of this one, but this one keeps coming up in search, so I'm thinking I may be missing something.

I am using a 3rd party lib that calls xmlhttprequest (browser), and I would like to run some automated tests on it using node. I was thinking of polyfilling node with an implementation of xmlhttprequest. I am using browserify to build. I can't change the implementation of the 3rd-party lib. I had something like this in mind:

```
//package.json

{
  server: {
    'XMLHTTPRequest': 'server-polyfill-of-xmlhttprequest'
  }
}
```

I don't think `server` exists though. Is there any way to use xhr to accomplish that?

Thanks!

**Comment by naugtur** [comment]
If you were using `xhr` for http request you could replace it with `request` in node.

If you want to keep the library, the only idea I have is to use xmlhttprequest mocking from sinon. you might have to create a fake global object and then

**Comment by thinkloop** [comment]
The thing is I actuallly want the request to go trhough, I want to test the service over the web. I would like to provide the dependent component a working reference to `window.XMLHTTPRequest`.

**Comment by naugtur** [comment]
There, I googled it for you :p

https://www.npmjs.com/package/xmlhttprequest
