### ISSUE TITLE
Incorrect body being sent when opts.body and opts.data are undefined and opts.json === true

### ISSUE THREAD

**Issue by djake** [naugtur/xhr#145]
When opts.body and opts.data are undefined and opts.json === true, requests are being sent with the string "null". This is because, in line 146, var body = options.body || options.data || null, resulting in JSON.stringify(null) on line 165, which returns the string.

See #144

**Comment by naugtur** [comment]
It might have been defaulted to null because if options.json is not set and body is undefined, some browser complained. 

#144 would have to be tested against the weird browsers we still support.

I'll dig through commits history later and see when it got added.

**Comment by naugtur** [comment]
sorry, misclick

**Comment by djake** [comment]
Ok I am happy to help with that if you can let me know what browsers we're talking about. 

If need be, I could change this PR so `JSON.stringify` is only called `if(body)`.

**Comment by naugtur** [comment]
The browsers I'd suspect are ie8 and up, old safaris starting at 5.1 as far as I remember and old Firefox 4.
Let's start by writing the test. Add it to the PR if you write it. I might get down to this tomorrow and then I'll put this on a branch where we can work together.

**Comment by naugtur** [comment]
Ok, I found where it came from.

https://github.com/naugtur/xhr/issues/100

How do we make both cases work?

**Comment by djake** [comment]
I think if I modify my PR to also add body = body || null just before xhr.send(body) (line 218), that should satisfy all needs. Does that work for you? I can include a comment linking back to #100 if that is helpful.

**Comment by naugtur** [comment]
Sounds like you nailed it!

A comment explaining why (Edge issue) and linking to #100 would be great.

**Comment by naugtur** [comment]
merged #144, fixed comment. Thanks for the contribution. Keep them coming! :)

**Comment by djake** [comment]
Would you mind publishing a new patch version to npm so we can get this fix into production? Thanks and happy new year!

**Comment by naugtur** [comment]
I was soooo AFK for the holidays. :)

published v2.3.3
