### ISSUE TITLE
Global settings needed for error handling, can you add some method for this?

### ISSUE THREAD

**Issue by hsuehic** [naugtur/xhr#146]
Global settings needed for error handling, can you add some method for this? Or some options for doing some thing for all requests bootstrapped by xhr. Thank you!

**Comment by naugtur** [comment]
I'd need to understand your use case better. 
With my current understanding I can suggest wrapping xhr in a function that adds what you need.

**Comment by hsuehic** [comment]
Thanks! I'll take you advice.
