### ISSUE TITLE
Mocking out response when running in browser testing

### ISSUE THREAD

**Issue by tejpowar** [naugtur/xhr#147]
Hi

I am writing some karma tests which need to mock out the response of the xhr request.

We are utilising this library to do a request and is wrapped around a promise. However when running in browser testing it seems it is instantiating a new window.XMLHTTPRequest as when i inspect it in the karma debugger for the XMLHttpRequest is not there for the URL i am trying to hit.

I have tried to add the following option as per docs

`xhr: window.XMLHttpRequest`

But then this breaks it and it hangs and does not get a response from the endpoint.

Any help or resolution on this would be great

**Comment by naugtur** [comment]
I can't get much information out of the writeup to be able to help.

There are multiple options, but before I start guessing what happened, just try putting this somewhere right after you plug in the thing you're using for requesting stuff:
```
xhr.XMLHttpRequest = MockXMLHttpRequest
```

**Comment by naugtur** [comment]
I assume you fixed it, since you didn't engage back. Feel free to reopen if needed.
