### ISSUE TITLE
Some more "no content" responses need fixed for Firefox

### ISSUE THREAD

**Issue by TehShrike** [naugtur/xhr#151]
Related to #111 

Reported by @Mouvedia in https://github.com/naugtur/xhr/pull/121#discussion_r95722286

In Firefox, 201/202/205 responses need to be manually fixed to not return XMLDocuments in the same way as 204 responses.

Relevant code: https://github.com/naugtur/xhr/blob/b9ba803a2800a16e30c5e6f7a208eba8143eb5cd/index.js#L233

**Comment by naugtur** [comment]
I wrote a test for this and it seems all 2xx responses return the same XML in FF
Even if I return an empty body from a 200OK I get the XML document. 

Adding more codes doesn't fix situations where someone is expecting an empty response from a 2xx that might not be empty and we can't automatically clear that. 

I think we'll have to duck-type the XML document to see if it's the one FF returns

**Comment by Mouvedia** [comment]
> Even if I return an empty body from a 200OK I get the XML document.

That's the case in older FF versions. The `documentElement` is called parsererror though.
I am expecting to add a fix in my own library in the coming days; if you don't patch it in the meantime, just copy it.

**Comment by naugtur** [comment]
I can patch and release real quick or accept a fix. If you can help me speed this up, maybe you don't need to fix it in your lib at all.

I'm trying to figure out what the best choice of response is here.

**Comment by Mouvedia** [comment]
> maybe you don't need to fix it in your lib at all.

I do. But I wanted to share my findings.

**Comment by naugtur** [comment]
great, I always appreciate more knowledge about quirks we could abstract away
