### ISSUE TITLE
npm website still references https://github.com/Raynos/xhr

### ISSUE THREAD

**Issue by ianwremmel** [naugtur/xhr#155]
Not sure if it matters or which url is preferable, but https://www.npmjs.com/package/xhr still points at the old repo url (though github redirects it correctly).

**Comment by naugtur** [comment]
I updated it in package.json not long ago, maybe it didn't catch up. I'll look into it

**Comment by naugtur** [comment]
The updated url was in an unreleased package.json
thx for noticing
