### ISSUE TITLE
Problem with getXml function

### ISSUE THREAD

**Issue by zharkov-eu** [naugtur/xhr#171]
responseType = "text", 204 No Content.
Problem with firefoxBugTakenEffect.
Failed to read the 'responseXML' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'document' (was 'text').

**Comment by naugtur** [comment]
Would you like to make a pull request maybe?
I'm currently taking care of a 12daysold on my own and I happened to have 3 minutes to write this while she sleeps.

**Comment by zharkov-eu** [comment]
Yes, i can do pull request, but if i forking master branch this error looks
like fixed, it wrapped on try/catch. Npm version doesn't have this part and
throw dom exception. I can replace try-catch by ternary if with return
operator, but i think that not required. Maybe all that you could do to fix
it - update npm version to master brunch?

11 дек. 2017 г. 3:13 PM пользователь "Zbyszek Tenerowicz" <
notifications@github.com> написал:

**Comment by naugtur** [comment]
Latest npm relese is the latest version tag on master. There might be something left to release. I'll check later.

**Comment by naugtur** [comment]
Published 2.4.1
Please check it out and help me verify it's fine. I'm still on duty as a stay at home dad.

**Comment by naugtur** [comment]
assuming fine.
