### ISSUE TITLE
XHR with webpack resolve - usage with Sinon

### ISSUE THREAD

**Issue by guzmo** [naugtur/xhr#175]
Hey,

I'm using XHR to support both node and browsers but when I'm trying to do the browser tests, using karma-webpack, it doesn't seem like Sinon is mocking the imported "request". 
I've got this in my karma.webpack.config.js.
```
resolve: {
     root: path.resolve('./src'),
     extensions: ['', '.js'],
     alias: {
          "request$": "xhr"
     }
},
```
When I'm running a regular XmlHttpRequest in my file it works and the response is mocked.
Any ideas how to use your XHR with Sinon to mock requests?
Or could you guide me to another mocking library I can use to mock both of the scenarios while using your library?

/ Cheers

**Comment by naugtur** [comment]
`xhr` holds a reference to XMLHttpRequest that it gets on initial execution of the module, so sinon mocks it too late. You need to override the cached reference with the new, mocked one, as documented here: See https://github.com/naugtur/xhr#mocking-requests

```
xhr.XMLHttpRequest = XMLHttpRequest
```
