### ISSUE TITLE
PATCH method support in typescript

### ISSUE THREAD

**Issue by tyam** [naugtur/xhr#176]
In typescript, Using xhr with PATCH method raises the following compile error.

> TS2322: Type '{ url: string; method: "PATCH"; ... }' is not assignable to type 'XhrUrlConfig'.

Adding 'PATCH' on XhrUrlConfig.method will fix this issue.

**Comment by naugtur** [comment]
A PR would be less work than writing the issue ;)

I'm busy organizing a conference and might not have time to do it soon. But I will unless you beat me to it.
