### ISSUE TITLE
Is this bug limited to VBScript?

### ISSUE THREAD

**Issue by Mouvedia** [naugtur/xhr#177]
https://web.archive.org/web/20060820125233/http://support.microsoft.com/kb/234486/en-us
affected versions of MSXML: 2.6, 3.0, 3.0 sp1

**Comment by naugtur** [comment]
You don't seem to be using the JavaScript package in this repository. This is not a place for XMLHttpRequest itself. Feel free to reopen if this is an issue with the package from this repository.

**Comment by Mouvedia** [comment]
Since VBScript often shares the same bugs as JScript, I was wondering if it was affected as well.
